### ISSUE TITLE
Star https://s3.amazonaws.com/biodata/genomes/GRCh37-star.tar.xz not found

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen-vm#104]
I was trying to reinstall star and I get the error message that the GRCh37-star.tar.xz is not there.

bowtie2 work fine.

Thanks!

bash-3.2$ bcbio_vm.py install --data --genomes GRCh37 --aligners bwa --aligners star
[2015-08-18 15:05] DEBUG: bcbio-nextgen: Running in docker container: 14afe6cd30bbef996286273c393fc7661d6cbe4c93265b6af87b6be4ec3c0a98
[2015-08-18 15:05] DEBUG: bcbio-nextgen-commands: docker attach --no-stdin 14afe6cd30bbef996286273c393fc7661d6cbe4c93265b6af87b6be4ec3c0a98
[2015-08-18 15:05] DEBUG: bcbio-nextgen-stdout: Cloning into 'cloudbiolinux'...
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: INFO: <cloudbio.flavor.Flavor instance at 0x7fed65bbbef0>
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: INFO: This is a ngs_pipeline_minimal flavor
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: INFO: Reading default fabricrc.txt
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: DBG [config.py]: Using config file /tmpbcbio-install/cloudbiolinux/cloudbio/../config/fabricrc.txt
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: INFO: Distribution __auto__
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: INFO: Get local environment
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: INFO: Ubuntu setup
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: DBG [distribution.py]: Debian-shared setup
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: DBG [distribution.py]: Source=trusty
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: DBG [distribution.py]: Checking target distribution ubuntu
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: DBG [distribution.py]: NixPkgs: Ignored
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: INFO: Now, testing connection to host...
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: INFO: Connection to host appears to work!
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: DBG [utils.py]: Expand paths
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'star'], 'genomes': [{'rnaseq': True, 'dbsnp': True, 'name': 'Human (GRCh37)', 'dbkey': 'GRCh37', 'annotations': ['battenberg', 'GA4GH_problem_regions', 'MIG']}], 'install_uniref': False}'): Human (GRCh37)
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: INFO: Genome preparation method ggd failed, trying next
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: INFO: Downloading genome from s3: GRCh37 star
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: --2015-08-18 15:06:07--  https://s3.amazonaws.com/biodata/genomes/GRCh37-star.tar.xz
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.1.248
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.1.248|:443... connected.
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: HTTP request sent, awaiting response... 404 Not Found
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: 2015-08-18 15:06:08 ERROR 404: Not Found.
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: 
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: 
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O GRCh37-star.tar.xz 'https://s3.amazonaws.com/biodata/genomes/GRCh37-star.tar.xz''
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: 
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: INFO: Genome preparation method s3 failed, trying next
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: INFO: Preparing genome GRCh37 with index star
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: Aug 18 15:06:08 ..... Started STAR run
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: Aug 18 15:06:08 ... Starting to generate Genome files
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: terminate called after throwing an instance of 'std::bad_alloc'
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:   what():  std::bad_alloc
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: Aborted
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: 
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: Fatal error: local() encountered an error (return code 134) while executing 'STAR --genomeDir /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/star --genomeFastaFiles /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --runThreadN 1 --runMode genomeGenerate --sjdbOverhang 99 --sjdbGTFfile /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/../rnaseq/ref-transcripts.gtf --genomeSAindexNbases 14'
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: 
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: Aborting.
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: INFO: Genome preparation method raw failed, trying next
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: Upgrading bcbio-nextgen data files
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: Setting up virtual machine
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: [localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: [localhost] local: cat /proc/version
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: [localhost] local: cat /etc/issue
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: [localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: [localhost] local: echo $HOME
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: [localhost] local: uname -m
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: [localhost] local: pwd
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: [localhost] local: echo $HOME
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: [localhost] local: mkdir -p '/root/tmp/cloudbiolinux/85764b26-d94d-3f54-8ba1-cc2e6db5dfd1'
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: [localhost] local: wget --continue --no-check-certificate -O GRCh37-star.tar.xz 'https://s3.amazonaws.com/biodata/genomes/GRCh37-star.tar.xz'
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: [localhost] local: mkdir /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/star
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: [localhost] local: STAR --genomeDir /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/star --genomeFastaFiles /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --runThreadN 1 --runMode genomeGenerate --sjdbOverhang 99 --sjdbGTFfile /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/../rnaseq/ref-transcripts.gtf --genomeSAindexNbases 14
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: Traceback (most recent call last):
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:   File "/usr/local/bin/bcbio_nextgen.py", line 207, in <module>
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:     install.upgrade_bcbio(kwargs["args"])
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 94, in upgrade_bcbio
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:     upgrade_bcbio_data(args, REMOTES)
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 254, in upgrade_bcbio_data
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:     cbl_deploy.deploy(s)
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:   File "/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:     _setup_vm(options, vm_launcher, actions)
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:   File "/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:     configure_instance(options, actions)
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:   File "/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 266, in configure_instance
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:     setup_biodata(options)
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:   File "/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 248, in setup_biodata
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:     install_proc(options["genomes"], ["ggd", "s3", "raw"])
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:   File "/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 350, in install_data
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:     _prep_genomes(env, genomes, genome_indexes, ready_approaches)
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:   File "/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 488, in _prep_genomes
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:     raise IOError("Could not prepare index {0} for {1} by any method".format(idx, gid))
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: IOError: Could not prepare index star for GRCh37 by any method
[2015-08-18 15:06] ERROR: bcbio-nextgen: Uncaught exception occurred
Traceback (most recent call last):
  File "/Users/alessandro/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.2a0-py2.7.egg/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/Users/alessandro/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.2a0-py2.7.egg/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'docker attach --no-stdin 14afe6cd30bbef996286273c393fc7661d6cbe4c93265b6af87b6be4ec3c0a98
Cloning into 'cloudbiolinux'...
INFO: <cloudbio.flavor.Flavor instance at 0x7fed65bbbef0>
INFO: This is a ngs_pipeline_minimal flavor
INFO: Reading default fabricrc.txt
DBG [config.py]: Using config file /tmpbcbio-install/cloudbiolinux/cloudbio/../config/fabricrc.txt
INFO: Distribution __auto__
INFO: Get local environment
INFO: Ubuntu setup
DBG [distribution.py]: Debian-shared setup
DBG [distribution.py]: Source=trusty
DBG [distribution.py]: Checking target distribution ubuntu
DBG [distribution.py]: NixPkgs: Ignored
INFO: Now, testing connection to host...
INFO: Connection to host appears to work!
DBG [utils.py]: Expand paths
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'star'], 'genomes': [{'rnaseq': True, 'dbsnp': True, 'name': 'Human (GRCh37)', 'dbkey': 'GRCh37', 'annotations': ['battenberg', 'GA4GH_problem_regions', 'MIG']}], 'install_uniref': False}'): Human (GRCh37)
INFO: Genome preparation method ggd failed, trying next
INFO: Downloading genome from s3: GRCh37 star
--2015-08-18 15:06:07--  https://s3.amazonaws.com/biodata/genomes/GRCh37-star.tar.xz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.1.248
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.1.248|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-08-18 15:06:08 ERROR 404: Not Found.

Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O GRCh37-star.tar.xz 'https://s3.amazonaws.com/biodata/genomes/GRCh37-star.tar.xz''

INFO: Genome preparation method s3 failed, trying next
INFO: Preparing genome GRCh37 with index star
Aug 18 15:06:08 ..... Started STAR run
Aug 18 15:06:08 ... Starting to generate Genome files
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

Fatal error: local() encountered an error (return code 134) while executing 'STAR --genomeDir /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/star --genomeFastaFiles /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --runThreadN 1 --runMode genomeGenerate --sjdbOverhang 99 --sjdbGTFfile /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/../rnaseq/ref-transcripts.gtf --genomeSAindexNbases 14'

Aborting.
INFO: Genome preparation method raw failed, trying next
Upgrading bcbio-nextgen data files
Setting up virtual machine
[localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
[localhost] local: cat /proc/version
[localhost] local: cat /etc/issue
[localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
[localhost] local: echo $HOME
[localhost] local: uname -m
[localhost] local: pwd
[localhost] local: echo $HOME
[localhost] local: mkdir -p '/root/tmp/cloudbiolinux/85764b26-d94d-3f54-8ba1-cc2e6db5dfd1'
[localhost] local: wget --continue --no-check-certificate -O GRCh37-star.tar.xz 'https://s3.amazonaws.com/biodata/genomes/GRCh37-star.tar.xz'
[localhost] local: mkdir /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/star
[localhost] local: STAR --genomeDir /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/star --genomeFastaFiles /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --runThreadN 1 --runMode genomeGenerate --sjdbOverhang 99 --sjdbGTFfile /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/../rnaseq/ref-transcripts.gtf --genomeSAindexNbases 14
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 94, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 254, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 266, in configure_instance
    setup_biodata(options)
  File "/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 248, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 350, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 488, in _prep_genomes
    raise IOError("Could not prepare index {0} for {1} by any method".format(idx, gid))
IOError: Could not prepare index star for GRCh37 by any method
' returned non-zero exit status 1
Stopping docker container

**Comment by chapmanb** [comment]
Sorry about the issue. We don't have pre-built indices for STAR because they are extremely large. The installer correctly skips this and tries to build the index on your machine but fails:
```
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: Aug 18 15:06:08 ..... Started STAR run
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: Aug 18 15:06:08 ... Starting to generate Genome files
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: terminate called after throwing an instance of 'std::bad_alloc'
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: what(): std::bad_alloc
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: Aborted
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout:
[2015-08-18 15:06] DEBUG: bcbio-nextgen-stdout: Fatal error: local() encountered an error (return code 134) while executing 'STAR --genomeDir /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/star --genomeFastaFiles /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --runThreadN 1 --runMode genomeGenerate --sjdbOverhang 99 --sjdbGTFfile /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/../rnaseq/ref-transcripts.gtf --genomeSAindexNbases 14'
```
The most likely cause of this is memory on the machine. STAR needs quite a bit of memory, I believe 64Gb, to build an index. It also needs a lot of memory to run, so you'll probably need to build this on a machine with more memory resources available. Does that make sense with the system you're trying to run this on?

**Comment by apastore** [comment]
Sure… I just have allocate 16GB I will run with 64!

Thanks and sorry for all the request !
