### ISSUE TITLE
gatk bcbio_vm not found

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen-vm#109]
Sorry Chapmanb, I need your help and this is not an issues, but i can not figure out how to load the gatk 
i am testing bcbbio vm on a local cluster.
i have copied GenomeAnalysisTK.jar in both a s3 bucket and in the bcbbio-vm data folder

and I have modified the  bcbio_system.yaml adding dir or jar 
resource:
gatk:
    dir: ~/install/bcbio-vm/data/GenomeAnalysisTK
or
    jar: http://s3-us-west-2.amazonaws.com/gatk/GenomeAnalysisTK.jar
or
   jar: s3://s3-us-west-2.amazonaws.com/gatk/GenomeAnalysisTK.jar

in both case i can not access the gatk jar.

could you please explain what i am doing wrong?

is not possible to mount the gatk directory like the work directory or the galaxy directory?

or run the docker images with something like 

docker run -it -v /local/gatk/folder:/usr/local/share/java/gatk chapmanb/bcbio-nextgen-devel

Thanks!

Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 164, in run
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 167, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 138, in variantcall_sample
    return genotype.variantcall_sample(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 250, in variantcall_sample
    call_file = caller_fn(align_bams, items, sam_ref, assoc_files, region, call_file)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/gatk.py", line 57, in unified_genotyper
    region, out_file)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/gatk.py", line 35, in _shared_gatk_call_prep
    for a in annotation.get_gatk_annotations(config):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/annotation.py", line 26, in get_gatk_annotations
    if broad_runner.gatk_type() == "restricted":
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 322, in gatk_type
    if LooseVersion(self.gatk_major_version()) > LooseVersion("2.3"):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 333, in gatk_major_version
    full_version = self.get_gatk_version()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 305, in get_gatk_version
    gatk_jar = self._get_jar("GenomeAnalysisTK", ["GenomeAnalysisTKLite"])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 384, in _get_jar
    raise ValueError("Could not find jar %s in %s:%s" % (command, self._picard_ref, self._gatk_dir))
ValueError: Could not find jar GenomeAnalysisTK in /usr/local/share/java/picard:/usr/local/share/java/gatk

**Comment by chapmanb** [comment]
Sorry about the confusion. I see two issues with your specification -- you want this to be under `resources` instead of `resource` and the path to the s3 bucket for non-us-east regions is not correct. I added an example to the documentation in this section to try and help:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/cloud.html#extra-software

It hopefully should work for you with:
```
resources:
  gatk:
    jar: s3://gatk@us-west-2/GenomeAnalysisTK.jar
```
Where `gatk` is the bucket name you put the jar in. Hope this works for you.
