### ISSUE TITLE
Errors downloading bcbio-nextgen docker image using bcbio_vm.py

### ISSUE THREAD

**Issue by brainstorm** [chapmanb/bcbio-nextgen-vm#131]
Brad, while writing this I realized what was the issue, so now this is for the record, just in case some user reports it... I was trying to run locally:

`bcbio_vm.py --datadir=~.bcbio/install/bcbio-vm/data install --data --tools`

After upgrading the wrapper via:

`bcbio_vm.py update --wrapper`

But then the boot2docker machine does not catch up with DNS and all attemps to import the docker image fail:

```
Romans-Air:bcbio-nextgen-vm romanvg$ bcbio_vm.py --datadir=~.bcbio/install/bcbio-vm/data install --data --tools
Retrieving bcbio-nextgen docker image with code and tools
Downloading from https://s3.amazonaws.com/bcbio_nextgen/bcbio-nextgen-docker-image.gz
Get https://s3.amazonaws.com/bcbio_nextgen/bcbio-nextgen-docker-image.gz: dial tcp: lookup s3.amazonaws.com on 10.255.248.1:53: read udp 10.255.248.1:53: i/o timeout
Traceback (most recent call last):
  File "/Users/romanvg/anaconda/bin/bcbio_vm.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen-vm==0.1.0a0', 'bcbio_vm.py')
  File "/Users/romanvg/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/romanvg/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/romanvg/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/EGG-INFO/scripts/bcbio_vm.py", line 303, in <module>

  File "/Users/romanvg/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/EGG-INFO/scripts/bcbio_vm.py", line 35, in cmd_install

  File "/Users/romanvg/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/bcbiovm/docker/install.py", line 26, in full
  File "/Users/romanvg/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/bcbiovm/docker/install.py", line 78, in pull
  File "/Users/romanvg/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'import', 'https://s3.amazonaws.com/bcbio_nextgen/bcbio-nextgen-docker-image.gz', 'chapmanb/bcbio-nextgen-devel']' returned non-zero exit status 1
```

From outside boot2docker, it obviously works:

```
Romans-Air:bcbio-nextgen-vm romanvg$ wget https://s3.amazonaws.com/bcbio_nextgen/bcbio-nextgen-docker-image.gz
--2015-11-03 16:52:48--  https://s3.amazonaws.com/bcbio_nextgen/bcbio-nextgen-docker-image.gz
Resolving s3.amazonaws.com... 54.231.13.232
Connecting to s3.amazonaws.com|54.231.13.232|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1961786472 (1.8G) [binary/octet-stream]
Saving to: 'bcbio-nextgen-docker-image.gz'

bcbio-nextgen-docker-image.gz                      0%[                                                                                                          ]   3.40M  1.35MB/s             ^C
```

Solution: reboot boot2docker if you change networks (went from wireless to wired).

**Comment by chapmanb** [comment]
Roman -- thanks for identifying the problem. If you have a chance it would be great to add the "restart boot2docker on a new network" tip to the OSX details in the README: https://github.com/chapmanb/bcbio-nextgen-vm#mac-osx-docker-support
