### ISSUE TITLE
Amazon S3 bcbio_vm.py aws vpc error

### ISSUE THREAD

**Issue by mortunco** [chapmanb/bcbio-nextgen-vm#143]
Hi,

I am coming across a problem while following the steps of bcbio_vm.py AWS setup. I have set my AIM key and secret key. 

Thanks in advance,

Best.
Tunc.

```
[ec2-user@ip-172-31-59-88 ~]$ bcbio_vm.py aws vpc
ERROR:gc3.elasticluster:Ignoring cluster `bcbio`: section cloud/amazon-us-east-1: length of value must be at least 1 for dictionary value @ data['ec2_access_key'], section cloud/amazon-us-east-1: length of value must be at least 1 for dictionary value @ data['ec2_secret_key']
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_vm.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen-vm==0.1.0a0', 'bcbio_vm.py')
  File "/home/ec2-user/install/bcbio-vm/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
    
  File "/home/ec2-user/install/bcbio-vm/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1491, in run_script
    
  File "/home/ec2-user/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/EGG-INFO/scripts/bcbio_vm.py", line 307, in <module>
    
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/vpc.py", line 14, in bootstrap
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/vpc.py", line 48, in _setup_vpc
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/common.py", line 97, in ecluster_config
  File "/home/ec2-user/install/bcbio-vm/anaconda/lib/python2.7/site-packages/elasticluster/conf.py", line 135, in fromConfig
    conf = config_reader.read_config()
  File "/home/ec2-user/install/bcbio-vm/anaconda/lib/python2.7/site-packages/elasticluster/conf.py", line 707, in read_config
    raise errors
voluptuous.MultipleInvalid: section cloud/amazon-us-east-1: length of value must be at least 1 for dictionary value @ data['ec2_access_key']
```

**Comment by mortunco** [comment]
```
[ec2-user@ip-172-31-59-88 ~]$ bcbio_vm.py aws iam --recreate
User credentials for bcbio:
 access_key_id: ########
 secret_access_key: ###
Instance profile: bcbio_full_s3_access

Wrote elasticluster config file at: /home/ec2-user/.bcbio/elasticluster/config
[ec2-user@ip-172-31-59-88 ~]$ bcbio_vm.py aws vpc
VPC bcbio already exists. Skipping. Use --recreate to re-create if needed.
Placement group bcbio_cluster_pg already exists. Skipping
```
I tried to recreate option and i guess it went without problem ? If I am right could you explain why did that initial error occur?

**Comment by mortunco** [comment]
I faced with this error during the following the next step. I believe it might be related with the error above. I apologise for asking 3 rapid questions. You may consider them as a series of error during the process.

Thank you very much for your time again.

Best regards,

Tunc.

```
[ec2-user@ip-172-31-59-88 data]$ bcbio_vm.py aws cluster bootstrap

PLAY [Docker installation] **************************************************** 

GATHERING FACTS *************************************************************** 
ok: [frontend001]
ok: [compute001]
ok: [compute002]

TASK: [Install docker dependencies] ******************************************* 
ok: [compute001] => (item=apt-transport-https)
ok: [frontend001] => (item=apt-transport-https)
ok: [compute002] => (item=apt-transport-https)

TASK: [Add docker apt repo (deb)] ********************************************* 
changed: [frontend001]
changed: [compute002]
changed: [compute001]

TASK: [Add docker apt key (deb)] ********************************************** 
changed: [compute001]
changed: [compute002]
changed: [frontend001]

TASK: [Install Docker (deb)] ************************************************** 
ok: [compute001] => (item=docker-engine)
ok: [frontend001] => (item=docker-engine)
ok: [compute002] => (item=docker-engine)

TASK: [Add docker yum repo (rpm)] ********************************************* 
skipping: [frontend001]
skipping: [compute001]
skipping: [compute002]

TASK: [Install Docker (rpm)] ************************************************** 
skipping: [compute001]
skipping: [compute002]
skipping: [frontend001]

TASK: [Add current user to the docker group] ********************************** 
ok: [frontend001]
ok: [compute001]
ok: [compute002]

TASK: [Restart Docker server] ************************************************* 
changed: [frontend001]
changed: [compute001]
changed: [compute002]

PLAY [Install gof3r] ********************************************************** 

GATHERING FACTS *************************************************************** 
ok: [frontend001]
ok: [compute001]
ok: [compute002]

TASK: [Prep gof3r release directory] ****************************************** 
ok: [frontend001]
ok: [compute001]
ok: [compute002]

TASK: [Prep local bin directory] ********************************************** 
ok: [frontend001]
ok: [compute001]
ok: [compute002]

TASK: [Get latest gof3r release] ********************************************** 
ok: [frontend001]
ok: [compute001]
ok: [compute002]

TASK: [Unpack gof3r release] ************************************************** 
ok: [frontend001]
ok: [compute002]
ok: [compute001]

TASK: [Install gof3r binary] ************************************************** 
ok: [frontend001]
ok: [compute001]
ok: [compute002]

PLAY [Mount encrypted filesystem on NFS server] ******************************* 

GATHERING FACTS *************************************************************** 
ok: [frontend001]

TASK: [Ensure {{encrypted_mount}} directory exists] *************************** 
ok: [frontend001]

TASK: [Format encrypted filesystem] ******************************************* 
ok: [frontend001] => (item={'options': 'rw,discard', 'uuid': '257a07b6-3770-4f94-ab92-1bc4e3fabe85', 'size_total': 20988547072, 'device': '/dev/xvda1', 'mount': '/', 'size_available': 9714282496, 'fstype': 'ext4'})
ok: [frontend001] => (item={'options': 'rw', 'uuid': '41454399-903a-4610-ba22-f48c49a33a7a', 'size_total': 15988584448, 'device': '/dev/xvdb', 'mount': '/mnt', 'size_available': 15129432064, 'fstype': 'ext3'})
ok: [frontend001] => (item={'options': 'rw,noatime,nodiratime', 'uuid': 'c09579db-d870-4c0c-beee-50933ae04749', 'size_total': 211244736512, 'device': '/dev/xvdf', 'mount': '/encrypted', 'size_available': 200428400640, 'fstype': 'ext4'})

TASK: [Mount encrypted filesystem] ******************************************** 
skipping: [frontend001]

TASK: [Ensure user can write to encrypted directory mount] ******************** 
skipping: [frontend001]

TASK: [Check if exportfs installed] ******************************************* 
changed: [frontend001]

TASK: [Add encrypted filesystem to exports] *********************************** 
ok: [frontend001]

PLAY [Mount NFS encrypted filesystem on compute nodes] ************************ 

GATHERING FACTS *************************************************************** 
ok: [compute002]
ok: [compute001]

TASK: [Ensure {{encrypted_mount}} directory exists] *************************** 
ok: [compute002]
ok: [compute001]

TASK: [configure /etc/fstab on clients for NFS encrypted directory] *********** 
ok: [compute002]
ok: [compute001]

TASK: [Ensure encrypted directory is mounted] ********************************* 
changed: [compute002]
changed: [compute001]

PLAY [Upgrade the host OS] **************************************************** 

GATHERING FACTS *************************************************************** 
ok: [frontend001]
ok: [compute002]
ok: [compute001]

TASK: [Upgrade to latest OS packages (apt)] *********************************** 
ok: [frontend001]
ok: [compute001]
ok: [compute002]

TASK: [Upgrade to latest OS packages (yum)] *********************************** 
skipping: [frontend001]
skipping: [compute001]
skipping: [compute002]

TASK: [Reboot] **************************************************************** 
skipping: [frontend001]
skipping: [compute001]
skipping: [compute002]

TASK: [Wait for instances to reboot] ****************************************** 
skipping: [frontend001]
skipping: [compute002]
skipping: [compute001]

PLAY [Install bcbio_vm] ******************************************************* 

GATHERING FACTS *************************************************************** 
ok: [frontend001]

TASK: [Get Miniconda install script] ****************************************** 
ok: [frontend001]

TASK: [Install Miniconda] ***************************************************** 
ok: [frontend001]

TASK: [Install bcbio_vm] ****************************************************** 
changed: [frontend001]

TASK: [bcbio_vm.py -- setgid docker] ****************************************** 
ok: [frontend001]

TASK: [Ensure slurmdbd started (deb)] ***************************************** 
ok: [frontend001]

TASK: [Ensure slurmdbd started (rpm)] ***************************************** 
skipping: [frontend001]

TASK: [Add handy alias for SLURM sacct] *************************************** 
ok: [frontend001]

PLAY [Update bcbio_vm tools] ************************************************** 

GATHERING FACTS *************************************************************** 
ok: [frontend001]
ok: [compute002]
ok: [compute001]

TASK: [install collectl for run stats (deb)] ********************************** 
ok: [frontend001]
ok: [compute001]
ok: [compute002]

TASK: [install collectl for run stats (rpm)] ********************************** 
skipping: [frontend001]
skipping: [compute001]
skipping: [compute002]

TASK: [Work around for occasional build problems in conda packages (directory)] *** 
ok: [frontend001]
ok: [compute001]
ok: [compute002]

TASK: [Work around for occasional build problems in conda packages (symlink)] *** 
ok: [frontend001]
ok: [compute001]
ok: [compute002]

TASK: [Install helpful supplemental tools (deb)] ****************************** 
ok: [frontend001] => (item=git,pigz,tmux,awscli)
ok: [compute001] => (item=git,pigz,tmux,awscli)
ok: [compute002] => (item=git,pigz,tmux,awscli)

TASK: [Install helpful supplemental tools (rpm)] ****************************** 
skipping: [frontend001]
skipping: [compute002]
skipping: [compute001]

TASK: [Ensure NFS directories are mounted] ************************************ 
changed: [frontend001]
changed: [compute001]
changed: [compute002]

TASK: [Add bcbio_vm.py to PATH] *********************************************** 
ok: [frontend001]
ok: [compute002]
ok: [compute001]

TASK: [Upgrade bcbio-vm docker container with tools] ************************** 
changed: [frontend001]
changed: [compute002]
changed: [compute001]
<job 684859974706.11012> finished on compute002
<job 684859974706.11087> finished on compute001
<job 684859974706.13015> finished on frontend001

TASK: [Save current configuration] ******************************************** 
changed: [frontend001]
failed: [compute001] => {"changed": true, "cmd": "bcbio_vm.py --datadir=~ubuntu/install/bcbio-vm/data saveconfig", "delta": "0:00:02.140948", "end": "2016-03-28 12:42:21.511476", "rc": 1, "start": "2016-03-28 12:42:19.370528", "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/local/bin/bcbio_vm.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen-vm==0.1.0a0', 'bcbio_vm.py')
  File "/home/ubuntu/install/bcbio-vm/data/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
    
  File "/home/ubuntu/install/bcbio-vm/data/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1491, in run_script
    
  File "/home/ubuntu/install/bcbio-vm/data/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/EGG-INFO/scripts/bcbio_vm.py", line 307, in <module>
    
  File "/home/ubuntu/install/bcbio-vm/data/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/EGG-INFO/scripts/bcbio_vm.py", line 108, in cmd_save_defaults
    
  File "build/bdist.linux-x86_64/egg/bcbiovm/docker/defaults.py", line 57, in save
TypeError: 'NoneType' object does not support item assignment
changed: [compute002]

TASK: [Add bcbio_system configuration file] *********************************** 
failed: [frontend001] => {"changed": true, "cmd": "mkdir ~ubuntu/install/bcbio-vm/data/galaxy && wget -O ~ubuntu/install/bcbio-vm/data/galaxy/bcbio_system.yaml --no-check-certificate https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/config/bcbio_system.yaml", "delta": "0:00:00.003547", "end": "2016-03-28 12:42:21.651677", "rc": 1, "start": "2016-03-28 12:42:21.648130", "warnings": ["Consider using file module with state=directory rather than running mkdir"]}
stderr: mkdir: cannot create directory ‘/home/ubuntu/install/bcbio-vm/data/galaxy’: File exists
failed: [compute002] => {"changed": true, "cmd": "mkdir ~ubuntu/install/bcbio-vm/data/galaxy && wget -O ~ubuntu/install/bcbio-vm/data/galaxy/bcbio_system.yaml --no-check-certificate https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/config/bcbio_system.yaml", "delta": "0:00:00.003349", "end": "2016-03-28 12:42:21.738341", "rc": 1, "start": "2016-03-28 12:42:21.734992", "warnings": ["Consider using file module with state=directory rather than running mkdir"]}
stderr: mkdir: cannot create directory ‘/home/ubuntu/install/bcbio-vm/data/galaxy’: File exists

FATAL: all hosts have already failed -- aborting
Failures: compute002 (1 failures), compute001 (1 failures), frontend001 (1 failures)
```

**Comment by chapmanb** [comment]
Tunc;
Sorry about the issues with starting and running the bcbio cluster on AWS. The first error looks like you might have run the original commands without the instance information set in environmental variables, so an incomplete elasticluster configuration file got created. Re-running looks to have solved that problem.

For the final error, that was a bug in bcbio_vm.py. I'll roll out the new fix first thing tomorrow (so you can update with `bcbio_vm.py upgrade --wrapper`) but this is nearly the last step in running your cluster so you can fix manually on your running machine by sshing to it: `bcbio_vm.py aws cluster ssh`, then doing:
```
wget -O ~ubuntu/install/bcbio-vm/data/galaxy/bcbio_system.yaml --no-check-certificate https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/config/bcbio_system.yaml
bcbio_vm.py devel system <cores> <memory>
```
where `<cores>` and `<memory>` match your AWS system from:

https://github.com/chapmanb/bcbio-nextgen-vm/blob/master/bcbiovm/aws/bootstrap.py#L13

Hope this works to get you started with analyses.
