### ISSUE TITLE
--no-check-certificate error 

### ISSUE THREAD

**Issue by firatuyulur** [chapmanb/bcbio-nextgen-vm#153]
Hi,
I managed to install bcbio with the following command to my computer at home and it works smooth. When I tried to use the same command at the computer at the office, I started to face different errors. first here is the command

sudo python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=//usr/local --isolate --genomes GRCh37 --aligners bwa --aligners bowtie2

Btw, an additional gatk upgrade was made according to the main source: https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html

-------------------------
The first error I had with installation to the office computer was caused by DNS configuration. Changing DNS fixed that issue. The error I cannot eliminate right now is a --no-check-certificate error. here is what I have at the prompt:

Running GGD recipe: transcripts
--2016-07-20 08:59:54--  https://s3.amazonaws.com/biodata/annotation/GRCh37-rnaseq-2015-12-01.tar.xz
s3.amazonaws.com (s3.amazonaws.com) çözümleniyor... 54.231.18.112
s3.amazonaws.com (s3.amazonaws.com)[54.231.18.112]:443 bağlanılıyor... bağlantı kuruldu.
HATA: s3.amazonaws.com sertifikası doğrulanamıyor. `CN=DigiCert Baltimore CA-2 G2,OU=www.digicert.com,O=DigiCert Inc,C=US' tarafından sağlanmış:
  Yerel olarak sağlayıcının kimliği doğrulanamaıyor.
s3.amazonaws.com adresine güvenliği gözardı ederek bağlanmak için `--no-check-certificate' seçeneğini kullanın.
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.9', 'bcbio_nextgen.py')
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
    
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
    
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.9-py2.7.egg-info/scripts/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 283, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/home/dna-lab/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/dna-lab/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/home/dna-lab/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/home/dna-lab/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/home/dna-lab/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 345, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/home/dna-lab/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 474, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/dna-lab/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 809, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file)
  File "/home/dna-lab/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/home/dna-lab/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/usr/local/share/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 5
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 245, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--isolate', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

I'm sorry that the language is Turkish but the error is clear to understand. Although it was able to download and execute other files from AWS like  osmic-v68-GRCh37.vcf.gz and human_ancestor.fa.gz, when it comes to GRCh37-rnaseq-2015-12-01.tar.xz, it asks for no-check-certificate.

I dont know how and which part of the python code I am supposed to enter --no-check-certificate to disable to security check. 

I check the firewall with:

sudo ufw status verbose

The status is "not active".

So, what should I do?
Thanks already.
Fırat

**Comment by chapmanb** [comment]
Firat;
Sorry about the issue. Some older versions of wget have problems resolving certificates, and I pushed a fix for this by adding `--no-check-certificate` to the transcript downloads. If you remove the temporary directory (`rm -rf tmpbcbio-install`) and re-run the install command it should pick up where it left off and hopefully finish cleanly. Thanks much for the report and hope this gets you going with bcbio.

**Comment by firatuyulur** [comment]
Thanks a lot, it works perfectly.
