### ISSUE TITLE
Unable to setup new cluster

### ISSUE THREAD

**Issue by kyubivela** [chapmanb/bcbio-nextgen-vm#160]
Hi guys, I need help on this. So I want to create new cluster for testing purpose with default setting:

```bash
[cloud/amazon-us-east-1]
provider=ec2_boto
ec2_url=https://ec2.us-east-1.amazonaws.com
ec2_access_key=keyhere
ec2_secret_key=secrethere
ec2_region=us-east-1
vpc=bcbio
request_floating_ip=True
instance_profile=bcbio_full_s3_access

[login/ubuntu]
image_user=ubuntu
# AWS Linux AMI
# image_user=ec2-user
image_user_sudo=root
image_sudo=True
user_key_name=bcbio
user_key_private=/home/pankaj/.bcbio/aws_keypairs/bcbio
user_key_public=/home/pankaj/.bcbio/aws_keypairs/bcbio.pub

[setup/ansible]
provider=ansible
frontend_groups=common

[setup/ansible-slurm]
provider=ansible
frontend_groups=slurm_master
compute_groups=slurm_clients
global_var_slurm_selecttype=select/cons_res
global_var_slurm_selecttypeparameters=CR_Core_Memory

[cluster/bcbio]
cloud=amazon-us-east-1
login=ubuntu
ssh_to=frontend
ssh_hostkeys_from_console_output=True
network_ids=bcbio_cluster
security_group=bcbio_cluster_sg
placement_group=bcbio_cluster_pg
image_id=ami-5ac2cd4d
#image_id=ami-4dfb5d26
root_volume_size=20
# AWS Linux AMI
# image_id=ami-b66ed3de
setup_provider=ansible-slurm
frontend_nodes=1
compute_nodes=1
flavor=c3.large
location = East US

[cluster/bcbio/frontend]
flavor=c3.large
encrypted_volume_size=20
#encrypted_volume_type=io1
#encrypted_volume_iops=3000
```

Everything is almost default, and I start the cluster as below:

```bash
~$ bcbio_vm.py aws cluster start
Starting cluster `bcbio` with 1 compute nodes.
Starting cluster `bcbio` with 1 frontend nodes.
(this may take a while...)
INFO:gc3.elasticluster:Starting node compute001.
INFO:gc3.elasticluster:Starting node frontend001.
INFO:gc3.elasticluster:_start_node: node has been started
INFO:gc3.elasticluster:_start_node: node has been started
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_vm.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen-vm==0.1.0a0', 'bcbio_vm.py')
  File "/home/pankaj/data/install/bcbio-vm/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/home/pankaj/data/install/bcbio-vm/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1491, in run_script
  File "/home/pankaj/data/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/EGG-INFO/scripts/bcbio_vm.py", line 320, in <module>

  File "/home/pankaj/data/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/bcbiovm/aws/cluster.py", line 117, in start
  File "/home/pankaj/data/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/bcbiovm/aws/common.py", line 88, in wrap_elasticluster
  File "/home/pankaj/data/install/bcbio-vm/anaconda/lib/python2.7/site-packages/elasticluster/main.py", line 181, in main
    app.run()
  File "/home/pankaj/data/install/bcbio-vm/anaconda/lib/python2.7/site-packages/cli/app.py", line 245, in run
    return self.post_run(returned)
  File "/home/pankaj/data/install/bcbio-vm/anaconda/lib/python2.7/site-packages/cli/app.py", line 241, in run
    returned = self.main(*args)
  File "/home/pankaj/data/install/bcbio-vm/anaconda/lib/python2.7/site-packages/elasticluster/main.py", line 169, in main
    return self.params.func()
  File "/home/pankaj/data/install/bcbio-vm/anaconda/lib/python2.7/site-packages/elasticluster/subcommands.py", line 71, in __call__
    return self.execute()
  File "/home/pankaj/data/install/bcbio-vm/anaconda/lib/python2.7/site-packages/elasticluster/subcommands.py", line 190, in execute
    cluster.start(min_nodes=min_nodes)
  File "/home/pankaj/data/install/bcbio-vm/anaconda/lib/python2.7/site-packages/elasticluster/cluster.py", line 415, in start
    keys, node.instance_id, node.ips)
  File "/home/pankaj/data/install/bcbio-vm/anaconda/lib/python2.7/site-packages/elasticluster/cluster.py", line 657, in _get_ssh_key_from_console_output
    known_hosts.add(name, type, entry.key)
AttributeError: 'NoneType' object has no attribute 'key'
```
Obviously there is something wrong with `_get_ssh_key_from_console_output`, but I can't pinpoint where it went wrong. The instances in AWS do spawn and I can manually ssh into those with above keys. 

Then I think, ok.. this might be failed setup phase; I also tried to `setup` again.

```bash
bcbio_vm.py aws cluster setup
Configuring cluster `bcbio`...
ERROR:gc3.elasticluster:the setup provider was not able to setup the cluster, but the cluster is running by now. Setup provider error message: `argument of type 'NoneType' is not iterable`
WARNING:gc3.elasticluster:Cluster `bcbio` not yet configured. Please, re-run `elasticluster setup bcbio` and/or check your configuration

WARNING: YOUR CLUSTER IS NOT READY YET!

Cluster name:     bcbio
Cluster template: bcbio
Default ssh to node: frontend001
- frontend nodes: 1
- compute nodes: 1

To login on the frontend node, run the command:

    elasticluster ssh bcbio

To upload or download files to the cluster, use the command:

    elasticluster sftp bcbio
```

Any help or hint is highly appreciated.

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for the report. It seems like something is problematic with your ssh key setup, although you're right that the elasticluster is not too helpful in resolving exactly what is going on. It might be worth recreating your config, IAM credentials and local keys with:
```
bcbio_vm.py aws iam --recreate
```
to see if something was problematic during that step (http://bcbio-nextgen.readthedocs.io/en/latest/contents/cloud.html#aws-setup). 

As an alternative to this setup if you can get by with single machines for your sample runs, we have been working on a simplified approach to running bcbio with a single ansible script:

https://github.com/chapmanb/bcbio-nextgen/tree/master/scripts/ansible

This has many fewer moving parts so is easier to debug at the cost of less automation. This might be an option if you keep running into issues with the more complicated cluster-based setup. Hope one of these approaches will get you running analyses.
