### ISSUE TITLE
problem after update

### ISSUE THREAD

**Issue by silvanopiazza** [chapmanb/bcbio-nextgen-vm#161]
Dear all,
after the last upgrade, I am not able to perform variant2 pipeline, because it stops after the alignment step.
from the log
```
[2017-01-22T02:03Z] Timing: variant calling
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 150, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 175, in parallel_variantcall_region
    to_process, extras = _dup_samples_by_variantcaller(samples)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 159, in _dup_samples_by_variantcaller
    samples = germline.split_somatic(samples)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/germline.py", line 29, in split_somatic
    if paired.normal_data:
AttributeError: 'NoneType' object has no attribute 'normal_data'
 returned non-zero exit status 1
```

ad the configuration:
```
details:
- algorithm:
    aligner: bwa
    mark_duplicates: false
    realign: false
    recalibrate: false
    variant_regions: /media/silvano/Disk1/install/bcbio-vm/data/bed/MODY_6_FINAL_1_Regions_Export_cleanfile.bed
    variantcaller: [freebayes, gatk-haplotype, samtools]
    ensemble:
     numpass: 2
  analysis: variant2
  description: 1_S1_L001
  files:
  - /media/silvano/Disk1/data/batch_004/data/data_ALL/1_S1_L001_R1_001.fastq.gz
  - /media/silvano/Disk1/data/batch_004/data/data_ALL/1_S1_L001_R2_001.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: batch4
    phenotype: normal
    sex: male
```

some could please have any suggestion? I already perform again all update steps again.
Best 
Silvano

**Comment by chapmanb** [comment]
Silvano;
Thanks for the report and sorry about the issue. The underlying problem is that you have a batch, `batch4` with a single sample labelled as `phenotype: normal`. `normal` and `tumor` are used for tumor/normal pairs so having a batch with a single `normal` confuses the logic that deals with these pairs. If this isn't a cancer sample where you need somatic calling, the right thing to do is to remove `phenotype: normal`, then it should proceed as intended. I also pushed a fix to avoid the confusing error to the latest development. Hope this gets it running smoothly for you.
