### ISSUE TITLE
Typo in bcbiovm/aws/common.py prevents starting a cluster

### ISSUE THREAD

**Issue by DavidQuigley** [chapmanb/bcbio-nextgen-vm#162]
As of 5/1/2016, installing from Miniconda2 as directed in the cloud documentation.

**Problem:**

Running *bcbio_vm.py aws cluster start* throws a NameError exception:
`NameError: global name 'ansible_utils' is not defined`

The traceback is:
```python
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_vm.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen-vm==0.1.0a0', 'bcbio_vm.py')
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/EGG-INFO/scripts/bcbio_vm.py", line 322, in <module>
    
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/cluster.py", line 120, in start
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/cluster.py", line 73, in bootstrap_cluster
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/bootstrap.py", line 46, in bootstrap
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/bootstrap.py", line 60, in _bootstrap_baseline
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/common.py", line 122, in run_ansible_pb
NameError: global name 'ansible_utils' is not defined
```
This prevents the cluster from starting.

**Likely cause**
Line 122 of bcbiovm/aws/common.py reads:

```python
if ansible.utils:
    ansible_utils.VERBOSITY = args.verbose - 1
```

I suspect this is a typo for *ansible.utils.VERBOSITY*. I commented lines 121-122 out and re-built my local copy of the egg, at which point my cluster was able to build completely.

**Comment by chapmanb** [comment]
David;
Thanks so much for the heads up and sorry about the typo. This is fixed in the development version and I'll push a new conda package as well. Thanks again.
