### ISSUE TITLE
 bcbio_vm.py aws cluster start  give 'ansible_utils' is not defined

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen-vm#163]
Hi Brad, I was just trying the aws implemetation of bcbio and  got this error. Thanks! 

Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/bin/bcbio_vm.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen-vm==0.1.0a0', 'bcbio_vm.py')
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/envs/bcbio-vm/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/envs/bcbio-vm/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/envs/bcbio-vm/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/EGG-INFO/scripts/bcbio_vm.py", line 322, in <module>
    
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/envs/bcbio-vm/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/bcbiovm/aws/icel.py", line 184, in create
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/envs/bcbio-vm/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/bcbiovm/aws/common.py", line 122, in run_ansible_pb
NameError: global name 'ansible_utils' is not defined
[1]+  Exit 1                  bcbio_vm.py aws cluster start

**Comment by apastore** [comment]
this what generate the error 
bcbio_vm.py aws icel create

**Comment by apastore** [comment]
also this generate the same error 
bcbio_vm.py aws cluster start

**Comment by apastore** [comment]
also when I ssh in the cluster with bcbio_vm.py aws cluster ssh
I do not see the /encrypted folder even if I star the cluster without lustre

NFS file system (no Lustre):

mkdir /encrypted/pastorea
mkdir: cannot create directory `/encrypted/pastorea': No such file or directory

Thanks!

**Comment by chapmanb** [comment]
Thanks for testing this out and sorry about the issues. Practically, it looks like you have an older version of bcbio-vm as this `ansible_utils` typo was fixed a few months ago (https://github.com/chapmanb/bcbio-nextgen-vm/commit/48899e74068c9177bfa81d96763548e0d1ed69d9#diff-858d17d4d306ec011658b187fe3f9020).

More generally, though, we're currently phasing out the custom AWS support in bcbio in favor of using AWS support from projects supporting the common workflow language. We haven't worked a lot on our AWS code in a while and there are better general implementations available we'd like to use like Toil's AWS support.

We're working on building out and testing this and should have more documentation and details soon. If you're AWS needs aren't immediate, waiting for better general support is probably a better plan at this point than trying to use the custom architecture. Would this work for your needs?

**Comment by apastore** [comment]
Definitely! Thanks a lot for your clarification!
