### ISSUE TITLE
aws cluster start crashes with 'no_reboot' AttributeError

### ISSUE THREAD

**Issue by gabwow** [chapmanb/bcbio-nextgen-vm#48]
Perhaps I'm just missing something obvious, but when I run:
% bcbio_vm.py aws cluster 
I get the error:
TASK: [Install gof3r binary] ************************************************** 
changed: [frontend001]
changed: [compute002]
changed: [compute001]
Traceback (most recent call last):
  File "/home/gabow/install/bcbio-vm/anaconda/bin/bcbio_vm.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen-vm==0.1.0a0', 'bcbio_vm.py')
  File "/home/gabow/install/bcbio-vm/anaconda/lib/python2.7/site-packages/setuptools-12.0.4-py2.7.egg/pkg_resources/__init__.py", line 696, in run_script
  File "/home/gabow/install/bcbio-vm/anaconda/lib/python2.7/site-packages/setuptools-12.0.4-py2.7.egg/pkg_resources/__init__.py", line 1621, in run_script
  File "/home/gabow/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/EGG-INFO/scripts/bcbio_vm.py", line 290, in <module>
    
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/cluster.py", line 117, in start
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/cluster.py", line 70, in bootstrap_cluster
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/bootstrap.py", line 33, in bootstrap
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/bootstrap.py", line 78, in _bootstrap_bcbio
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/common.py", line 124, in run_ansible_pb
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/bootstrap.py", line 75, in _extra_vars
AttributeError: 'Namespace' object has no attribute 'no_reboot'

I do not seem to get this error running
$ bcbio_vm.py aws cluster bootstrap

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the problem. We recently re-worked the commandline to be more consistent and missed propogating the `--no-reboot` option over. I pushed a fix to resolve this, so if you update with:
```
bcbio_vm.py upgrade --wrapper
```
it should now work correctly. Practically running `bcbio_vm.py aws bcbio bootstrap` after the failure also gets you a fully functional cluster so if you've already done that should be good to go.

Sorry about the issue and thanks again for the report.
