### ISSUE TITLE
The --image option - fails if you need the name/tag nomenclature

### ISSUE THREAD

**Issue by kern3020** [chapmanb/bcbio-nextgen-vm#51]
Hello, 

I like to use both a repository name and tag. For example, 

	jkern@yeast:~/bin$ docker images
	REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
	jkern/bcbio-dev     stable              f564b808b193        47 hours ago        3.837 GB

What is the right way to call bcbio_vm.py install with the --image option? 

If you use just the repository name(jkern/bcbio-dev), fails in 
bcbiovm/docker/manage.py(35)run_bcbio_cmd(). Effectively it calls...

	jkern@yeast:~/src$ docker run -t -i jkern/bcbio-dev /bin/bash
	Unable to find image 'jkern/bcbio-dev' locally
	Pulling repository jkern/bcbio-dev
	2015/02/11 23:01:00 HTTP code: 404

If you use both the repository name and(jkern/bcbio-dev:stable), it
fails in bcbiovm/docker/install.py(137)_check_docker_image()?

Here is a patch which takes the tag into consideration. 

	def _check_docker_image(a_image):
	    """Ensure docker image exists. """
	    a_tag=None
	    if ":" in a_image:
		(a_image,a_tag) = a_image.split(":")
	    for image in subprocess.check_output(["sudo", "docker", "images"]).split("\n"):
		parts = image.split()
		if len(parts) > 1 and parts[0] == a_image:
		    if not a_tag or a_tag and parts[1] == a_tag:
		        return
	    raise ValueError("Could not find docker image %s in local repository" % a_image)

Sorry I didn't submit via PR but my workspace is a mess. 

-jk

**Comment by mjsteinbaugh** [comment]
+1 I'd really like this functionality to pull down versioned bcbio images from quay.io:

```
bcbio_vm.py install --tools --image quay.io/bcbio/bcbio-vc:1.1.3-v1.1.3
```

This currently errors because of the `1.1.3-v1.1.3` tag:

```
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_vm.py", line 354, in <module>
    args.func(args)
  File "/usr/local/bin/bcbio_vm.py", line 40, in cmd_install
    install.full(args, devel.DOCKER)
  File "/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbiovm/docker/install.py", line 27, in full
    _check_docker_image(args)
  File "/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbiovm/docker/install.py", line 148, in _check_docker_image
    raise ValueError("Could not find docker image %s in local repository" % args.image)
ValueError: Could not find docker image quay.io/bcbio/bcbio-vc:1.1.3-v1.1.3 in local repository
```
