### ISSUE TITLE
error creating the lustre FS if cluster still starting (ithink)

### ISSUE THREAD

**Issue by lpantano** [chapmanb/bcbio-nextgen-vm#52]
Or i think that is. It is at the end when try to save .elasticluster/storage/icel-bcbiolustre.ssh_config, the storage folder/file doesn't exist yet.

Waiting for stack to launch (this will take a few minutes)..........................................................................................
Traceback (most recent call last):
  File "/home/lpantano/soft/myconda/bin/bcbio_vm.py", line 4, in <module>
      __import__('pkg_resources').run_script('bcbio-nextgen-vm==0.1.0a0', 'bcbio_vm.py')
        File "/home/lpantano/soft/myconda/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py", line 696, in run_script
          File "/home/lpantano/soft/myconda/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py", line 1621, in run_script
            File "/home/lpantano/soft/myconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/EGG-INFO/scripts/bcbio_vm.py", line 290, in <module>

              File "/home/lpantano/soft/myconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/bcbiovm/aws/icel.py", line 164, in create
                File "/home/lpantano/soft/myconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/bcbiovm/aws/icel.py", line 523, in _write_ssh_config
                IOError: [Errno 2] No such file or directory: '/home/lpantano/.elasticluster/storage/icel-bcbiolustre.ssh_config'

**Comment by chapmanb** [comment]
Lorena;
Thanks for the heads up on the problem. This was an issue with our new unified storage setup. I fixed so it should hopefully work as expected on future runs. Thanks again.
