### ISSUE TITLE
Completely remove bcbio-nextgen-vm

### ISSUE THREAD

**Issue by nstongcelmatix** [chapmanb/bcbio-nextgen-vm#92]
I've managed to screw up the AWS permissions somewhere along the way getting an error
>TypeError: __init__() takes exactly 1 argument (2 given)

from running
>bcbio_vm.py run -n 4 s3://bioinformaticsremap/test/test_head.yaml

I believe because there is no access to the s3 bucket.  I've tried removing and reinstalling but the problem persists.  There are issues with the  aws iam and aws vpc steps because of the user and groups set up on AWS already.  What do I have to remove from my AWS account to be able to reinstall cleanly?

**Comment by chapmanb** [comment]
Sorry about the issue. I'm not sure exactly where this error is coming from so don't have any specific suggestions about what to fix. It would be helpful if you could run in single core mode:
```
bcbio_vm.py run -n 1 s3://bioinformaticsremap/test/test_head.yaml
```
and post the full error traceback from bcbio. multicore runs (`-n 4`) can often obscure the causative error. Hopefully we'll be able to provide more useful suggestions knowing where it fails. Thanks much.

**Comment by nstongcelmatix** [comment]
Looks the same
ubuntu@frontend001:/encrypted/test/work$ bcbio_vm.py run -n 1 s3://bioinformaticsremap/test/test_head.yaml
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_vm.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen-vm==0.1.0a0', 'bcbio_vm.py')
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 735, in run_script
    
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 1659, in run_script
    
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/EGG-INFO/scripts/bcbio_vm.py", line 292, in <module>
    
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/EGG-INFO/scripts/bcbio_vm.py", line 37, in cmd_run
    
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/bcbiovm/docker/defaults.py", line 16, in update_check_args
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/bcbiovm/docker/defaults.py", line 32, in _handle_remotes
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/bcbiovm/aws/config.py", line 13, in load_s3
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.1a0-py2.7.egg/bcbio/distributed/objectstore.py", line 620, in open
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.1a0-py2.7.egg/bcbio/distributed/objectstore.py", line 445, in open
  File "/home/ubuntu/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.1a0-py2.7.egg/bcbio/distributed/objectstore.py", line 112, in __init__
TypeError: __init__() takes exactly 1 argument (2 given)

**Comment by chapmanb** [comment]
Thanks for the full traceback. Apologies, this is an error we introduced when refactoring to support other object stores. Alexandru pushed a fix which should hopefully resolve it:

https://github.com/chapmanb/bcbio-nextgen/commit/cacf21997b4d6a6a8febc836f3033eec5d3db770

You can upgrade to the fix with:
```
bcbio_vm.py upgrade --wrapper
```
Sorry again about the issue and please let us know if you have any other problems.
