### ISSUE TITLE
VEP 81

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen-vm#95]
first thanks for developing this tool!

I have tried to update bcbio with the latest version but after executing bcbio_vm.py install --data

I get the following error. I also tried to delete the old version ans install the new one but nothing change! 

I think is a issue on the veep install.pl command since in the docker image is the old vep 79  
Thanks for your support!

bash-3.2$ bcbio_vm.py install --data
[2015-07-24 18:48] DEBUG: bcbio-nextgen: Running in docker container: 5788eb89127499aad6e1aac316ef8ae05828f0ba919586730a879d2dd8aaf3ab
[2015-07-24 18:48] DEBUG: bcbio-nextgen-commands: docker attach --no-stdin 5788eb89127499aad6e1aac316ef8ae05828f0ba919586730a879d2dd8aaf3ab
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: Cloning into 'cloudbiolinux'...
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: INFO: <cloudbio.flavor.Flavor instance at 0x7fc241260518>
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: INFO: This is a ngs_pipeline_minimal flavor
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: INFO: Reading default fabricrc.txt
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: DBG [config.py]: Using config file /tmpbcbio-install/cloudbiolinux/cloudbio/../config/fabricrc.txt
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: INFO: Distribution __auto__
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: INFO: Get local environment
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: INFO: Ubuntu setup
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: DBG [distribution.py]: Debian-shared setup
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: DBG [distribution.py]: Source=trusty
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: DBG [distribution.py]: Checking target distribution ubuntu
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: DBG [distribution.py]: NixPkgs: Ignored
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: INFO: Now, testing connection to host...
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: INFO: Connection to host appears to work!
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: DBG [utils.py]: Expand paths
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa'], 'genomes': [{'rnaseq': True, 'dbsnp': True, 'name': 'Human (GRCh37)', 'dbkey': 'GRCh37', 'annotations': ['battenberg']}], 'install_uniref': False}'): Human (GRCh37)
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: [2015-07-24 18:48:47.362200] DEBUG: bcbio-nextgen: Prepare VEP directory for homo_sapiens_vep_81_GRCh37
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: [2015-07-24 18:48:47.362675] DEBUG: bcbio-nextgen-commands: /usr/local/bin/vep_install.pl -a c -s homo_sapiens_vep_81_GRCh37 -c /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/vep
[2015-07-24 18:48] DEBUG: bcbio-nextgen-stdout: [2015-07-24 18:48:47.916131] DEBUG: bcbio-nextgen: Getting list of available cache files
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: [2015-07-24 18:50:49.041482] DEBUG: bcbio-nextgen: Could not get current species list - using predefined list instead
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: [2015-07-24 18:50:49.041718] DEBUG: bcbio-nextgen: For more species, see http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: [2015-07-24 18:50:49.041913] DEBUG: bcbio-nextgen: ERROR: No matching species found at /usr/local/bin/vep_install.pl line 512.
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: [2015-07-24 18:50:49.051583] ERROR: bcbio-nextgen: Uncaught exception occurred
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: Traceback (most recent call last):
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:     _do_run(cmd, checks, log_stdout)
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:     raise subprocess.CalledProcessError(exitcode, error_msg)
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: CalledProcessError: Command '/usr/local/bin/vep_install.pl -a c -s homo_sapiens_vep_81_GRCh37 -c /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/vep
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: Getting list of available cache files
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: Could not get current species list - using predefined list instead
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: For more species, see http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: ERROR: No matching species found at /usr/local/bin/vep_install.pl line 512.
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: ' returned non-zero exit status 110
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: Traceback (most recent call last):
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:   File "/usr/local/bin/bcbio_nextgen.py", line 201, in <module>
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:     install.upgrade_bcbio(kwargs["args"])
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:     upgrade_bcbio_data(args, REMOTES)
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 252, in upgrade_bcbio_data
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:     _upgrade_vep_data(s["fabricrc_overrides"]["galaxy_home"], tooldir)
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 287, in _upgrade_vep_data
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: Upgrading bcbio-nextgen data files
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: Setting up virtual machine
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: [localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: [localhost] local: cat /proc/version
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: [localhost] local: cat /etc/issue
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: [localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: [localhost] local: echo $HOME
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: [localhost] local: uname -m
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:     effects.prep_vep_cache(dbkey, ref_file, tooldir)
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 92, in prep_vep_cache
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:     do.run(cmd, "Prepare VEP directory for %s" % ensembl_name)
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:     _do_run(cmd, checks, log_stdout)
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout:     raise subprocess.CalledProcessError(exitcode, error_msg)
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: subprocess.CalledProcessError: Command '/usr/local/bin/vep_install.pl -a c -s homo_sapiens_vep_81_GRCh37 -c /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/vep
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: Getting list of available cache files
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: Could not get current species list - using predefined list instead
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: For more species, see http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: ERROR: No matching species found at /usr/local/bin/vep_install.pl line 512.
[2015-07-24 18:50] DEBUG: bcbio-nextgen-stdout: ' returned non-zero exit status 110
[2015-07-24 18:50] ERROR: bcbio-nextgen: Uncaught exception occurred
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "build/bdist.linux-x86_64/egg/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'docker attach --no-stdin 5788eb89127499aad6e1aac316ef8ae05828f0ba919586730a879d2dd8aaf3ab
Cloning into 'cloudbiolinux'...
INFO: <cloudbio.flavor.Flavor instance at 0x7fc241260518>
INFO: This is a ngs_pipeline_minimal flavor
INFO: Reading default fabricrc.txt
DBG [config.py]: Using config file /tmpbcbio-install/cloudbiolinux/cloudbio/../config/fabricrc.txt
INFO: Distribution __auto__
INFO: Get local environment
INFO: Ubuntu setup
DBG [distribution.py]: Debian-shared setup
DBG [distribution.py]: Source=trusty
DBG [distribution.py]: Checking target distribution ubuntu
DBG [distribution.py]: NixPkgs: Ignored
INFO: Now, testing connection to host...
INFO: Connection to host appears to work!
DBG [utils.py]: Expand paths
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa'], 'genomes': [{'rnaseq': True, 'dbsnp': True, 'name': 'Human (GRCh37)', 'dbkey': 'GRCh37', 'annotations': ['battenberg']}], 'install_uniref': False}'): Human (GRCh37)
[2015-07-24 18:48:47.362200] DEBUG: bcbio-nextgen: Prepare VEP directory for homo_sapiens_vep_81_GRCh37
[2015-07-24 18:48:47.362675] DEBUG: bcbio-nextgen-commands: /usr/local/bin/vep_install.pl -a c -s homo_sapiens_vep_81_GRCh37 -c /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/vep
[2015-07-24 18:48:47.916131] DEBUG: bcbio-nextgen: Getting list of available cache files
[2015-07-24 18:50:49.041482] DEBUG: bcbio-nextgen: Could not get current species list - using predefined list instead
[2015-07-24 18:50:49.041718] DEBUG: bcbio-nextgen: For more species, see http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre
[2015-07-24 18:50:49.041913] DEBUG: bcbio-nextgen: ERROR: No matching species found at /usr/local/bin/vep_install.pl line 512.
[2015-07-24 18:50:49.051583] ERROR: bcbio-nextgen: Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command '/usr/local/bin/vep_install.pl -a c -s homo_sapiens_vep_81_GRCh37 -c /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/vep
Getting list of available cache files
Could not get current species list - using predefined list instead
For more species, see http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre
ERROR: No matching species found at /usr/local/bin/vep_install.pl line 512.
' returned non-zero exit status 110
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 201, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 252, in upgrade_bcbio_data
    _upgrade_vep_data(s["fabricrc_overrides"]["galaxy_home"], tooldir)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 287, in _upgrade_vep_data
Upgrading bcbio-nextgen data files
Setting up virtual machine
[localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
[localhost] local: cat /proc/version
[localhost] local: cat /etc/issue
[localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
[localhost] local: echo $HOME
[localhost] local: uname -m
    effects.prep_vep_cache(dbkey, ref_file, tooldir)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 92, in prep_vep_cache
    do.run(cmd, "Prepare VEP directory for %s" % ensembl_name)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/usr/local/bin/vep_install.pl -a c -s homo_sapiens_vep_81_GRCh37 -c /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/vep
Getting list of available cache files
Could not get current species list - using predefined list instead
For more species, see http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre
ERROR: No matching species found at /usr/local/bin/vep_install.pl line 512.
' returned non-zero exit status 110
' returned non-zero exit status 1
Stopping docker container

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. We recently updated the bcbio data files to support the latest Ensembl release, but also needed to update VEP in the container. I pushed a new Docker build with the latest set of tools including VEP supporting the version 81 release. If you update with:
```
bcbio_vm.py upgrade --tools
```
it should hopefully run cleanly now. Hope this gets everything working cleanly for you.
