### ISSUE TITLE
template with bam file

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen-vm#97]
Hi Chapmanb,

I was to run bcbbio-vm on already aligned BAM files. my yam configuration file is:

I receive the following error message I have seen if I link a fq file and then I modified the configuration file manually it run with out problem.

do you know what I am doing wrong?

Thanks!

details:
  - analysis: variant2
    genome_build: GRCh37
    # to do multi-sample variant calling, assign samples the same metadata / batch
    # metadata:
    #   batch: your-arbitrary-batch-name
    algorithm:
      aligner: false
      bam_clean: picard
      bam_sort: coordinate
      mark_duplicates: samtools
      recalibrate: false
      realign: false
      variantcaller: [vardict, mutect, freebayes]
      prioritize: true
      effects: vep
      ensemble:
       numpass: 2
      indelcaller: [scalpel, pindel, sid]
      # for targetted projects, set the region
      variant_regions: /Users/alessandro/install/bcbio-vm/data/bed/27327-1399408228_Covered.bed

$bcbio_vm.py template --only-metadata project1/config/project1-template.yaml project1.csv bam/*
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_vm.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen-vm==0.1.0a0', 'bcbio_vm.py')
  File "/usr/local/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 735, in run_script
    
  File "/usr/local/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 1659, in run_script
    
  File "/Users/alessandro/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg/EGG-INFO/scripts/bcbio_vm.py", line 292, in <module>
    
  File "/Users/alessandro/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.1a0-py2.7.egg/bcbio/workflow/template.py", line 388, in setup
  File "/Users/alessandro/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.1a0-py2.7.egg/bcbio/workflow/template.py", line 85, in _prep_items_from_base
  File "/Users/alessandro/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.1a0-py2.7.egg/bcbio/workflow/template.py", line 55, in _prep_bam_input
  File "/Users/alessandro/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.1a0-py2.7.egg/bcbio/bam/__init__.py", line 384, in sample_name
    
AttributeError: 'module' object has no attribute 'AlignmentFile'

**Comment by chapmanb** [comment]
Sorry about the issue. It seems like your bcbio-vm installation has an outdated pysam version without support for the recent changes in 0.8.x. I'm not sure why it didn't pull in the right version, but you could try updating it manually with:
```
/Users/alessandro/install/bcbio-vm/anaconda/bin/conda install -c bcbio pysam
```
which should hopefully get you the 0.8.3 version with support for `AlignmentFile`. Hope this fixes things for you.
