### ISSUE TITLE
prioritize Tumor only mutation with bcbio-vm 

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen-vm#98]
Hi Chapmanb,
I have seen you post on Blue collar bioinformatics on tumor only mutation prioritization.

I have set prioritize: true in the bcbio template file and I can generate a configuration file for the run,
but when I run bcbio-vm.py run ../config/project1.yaml

I get the following error message.

I have not find any mention to prioritize.py in the manual, but I would like to use it for a tumor only project.

bdw. is possible to use the Mutect PON option in bcbio?

Thanks!
```
Running in docker container: a4c6b047c5a8a9e7638ca1a3d94303939967c727ba151e3667ae0aeff4087d76

[2015-08-09T08:06Z] Resource requests: sambamba, samtools; memory: 2.00, 2.00; cores: 16, 16

[2015-08-09T08:06Z] Configuring 1 jobs to run, using 1 cores each with 2.00g of memory reserved for each job

[2015-08-09T08:06Z] Timing: organize samples

[2015-08-09T08:06Z] multiprocessing: organize_samples

[2015-08-09T08:06Z] Using input YAML configuration: /mnt/work/bcbio_sample-forvm.yaml

[2015-08-09T08:06Z] Checking sample YAML configuration: /mnt/work/bcbio_sample-forvm.yaml

Traceback (most recent call last):

  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>

    main(**kwargs)

  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main

    run_main(**kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main

    fc_dir, run_info_yaml)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel

    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 139, in run

    [x[0]["description"] for x in samples]]])

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel

    return run_multicore(fn, items, config, parallel=parallel)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore

    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__

    self.dispatch(function, args, kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch

    job = ImmediateApply(func, args, kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__

    self.results = func(*args, **kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper

    return apply(f, *args, **kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 200, in organize_samples

    return run_info.organize(*args)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 41, in organize

    run_details = _run_info_from_yaml(dirs, run_info_yaml, config, sample_names)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 601, in _run_info_from_yaml

    _check_sample_config(run_details, run_info_yaml, config)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 465, in _check_sample_config

    [_check_algorithm_keys(x) for x in items]

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 324, in _check_algorithm_keys

    % (problem_keys, ALG_DOC_URL))

ValueError: Unexpected configuration keyword in 'algorithm' section: ['prioritize']

See configuration documentation for supported options:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#algorithm-parameters



Uncaught exception occurred

Traceback (most recent call last):

  File "/Users/alessandro/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.1a0-py2.7.egg/bcbio/provenance/do.py", line 21, in run

    _do_run(cmd, checks, log_stdout)

  File "/Users/alessandro/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.1a0-py2.7.egg/bcbio/provenance/do.py", line 95, in _do_run

    raise subprocess.CalledProcessError(exitcode, error_msg)

CalledProcessError: Command 'docker attach --no-stdin a4c6b047c5a8a9e7638ca1a3d94303939967c727ba151e3667ae0aeff4087d76

[2015-08-09T08:06Z] Resource requests: sambamba, samtools; memory: 2.00, 2.00; cores: 16, 16

[2015-08-09T08:06Z] Configuring 1 jobs to run, using 1 cores each with 2.00g of memory reserved for each job

[2015-08-09T08:06Z] Timing: organize samples

[2015-08-09T08:06Z] multiprocessing: organize_samples

[2015-08-09T08:06Z] Using input YAML configuration: /mnt/work/bcbio_sample-forvm.yaml

[2015-08-09T08:06Z] Checking sample YAML configuration: /mnt/work/bcbio_sample-forvm.yaml

Traceback (most recent call last):

  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>

    main(**kwargs)

  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main

    run_main(**kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main

    fc_dir, run_info_yaml)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel

    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 139, in run

    [x[0]["description"] for x in samples]]])

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel

    return run_multicore(fn, items, config, parallel=parallel)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore

    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__

    self.dispatch(function, args, kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch

    job = ImmediateApply(func, args, kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__

    self.results = func(*args, **kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper

    return apply(f, *args, **kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 200, in organize_samples

    return run_info.organize(*args)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 41, in organize

    run_details = _run_info_from_yaml(dirs, run_info_yaml, config, sample_names)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 601, in _run_info_from_yaml

    _check_sample_config(run_details, run_info_yaml, config)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 465, in _check_sample_config

    [_check_algorithm_keys(x) for x in items]

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 324, in _check_algorithm_keys

    % (problem_keys, ALG_DOC_URL))

ValueError: Unexpected configuration keyword in 'algorithm' section: ['prioritize']

See configuration documentation for supported options:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#algorithm-parameters



' returned non-zero exit status 1

Stopping docker container
```

**Comment by chapmanb** [comment]
You don't need to specify anything for prioritization. It will happen automatically on tumor-only calls so you get both the original and prioritized VCFs. It is pretty low-cost in terms of computational time so we just enabled it by default for batches labelled as `phenotype: tumor` with no matching normal.

You can specify a panel of normals for MuTect with the `background` argument:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#variant-calling

Hope this helps.
