### ISSUE TITLE
DBI for VEP 81 missing

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen-vm#99]
Thanks for your previous response.

I have seen that the VEP 81 is complain for the Missing DBI 

I have installed in my container and it seem to work for me.

Thanks for you support I love bcbio!

[2015-08-09T04:41Z] Finalizing variant calls: 24, freebayes

[2015-08-09T04:41Z] Calculating variation effects for 24, freebayes

[2015-08-09T04:41Z] Ensembl variant effect predictor : 24

[2015-08-09T04:41Z] Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /usr/local/Cellar/vep/81_2015-07-23/lib/Plugins /usr/local/Cellar/vep/81_2015-07-23/lib /usr/local/bin /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.

[2015-08-09T04:41Z] BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.

[2015-08-09T04:41Z] Uncaught exception occurred

Traceback (most recent call last):

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run

    _do_run(cmd, checks, log_stdout)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run

    raise subprocess.CalledProcessError(exitcode, error_msg)

CalledProcessError: Command 'set -o pipefail; /usr/local/bin/variant_effect_predictor.pl --vcf -o stdout -i /mnt/work/freebayes/batch24.vcf.gz --fork 5 --species homo_sapiens --no_stats --cache --offline --dir /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/vep --sift b --polyphen b --symbol --numbers --biotype --total_length --canonical --ccds --fields Consequence,Codons,Amino_acids,Gene,SYMBOL,Feature,EXON,PolyPhen,SIFT,Protein_position,BIOTYPE,CANONICAL,CCDS,LoF,LoF_filter,LoF_flags --plugin LoF,human_ancestor_fa:/usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/variation/human_ancestor.fa.gz | sed '/^#/! s/;;/;/g' | bgzip -c > /mnt/work/freebayes/tx/tmpekR8KC/batch24-vepeffects.vcf.gz

Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /usr/local/Cellar/vep/81_2015-07-23/lib/Plugins /usr/local/Cellar/vep/81_2015-07-23/lib /usr/local/bin /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.

Compilation failed in require at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 68.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 68.

Compilation failed in require at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Registry.pm line 136.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Registry.pm line 136.

Compilation failed in require at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Variation/Utils/VEP.pm line 64.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Variation/Utils/VEP.pm line 64.

Compilation failed in require at /usr/local/bin/variant_effect_predictor.pl line 72.

BEGIN failed--compilation aborted at /usr/local/bin/variant_effect_predictor.pl line 72.

' returned non-zero exit status 2

Traceback (most recent call last):

  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>

    main(**kwargs)

  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main

    run_main(**kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main

    fc_dir, run_info_yaml)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel

    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 174, in run

    samples = run_parallel("postprocess_variants", samples)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel

    return run_multicore(fn, items, config, parallel=parallel)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore

    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__

    self.dispatch(function, args, kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch

    job = ImmediateApply(func, args, kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__

    self.results = func(*args, **kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper

    return apply(f, *args, **kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 68, in postprocess_variants

    return variation.postprocess_variants(*args)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/variation.py", line 18, in postprocess_variants

    ann_vrn_file, vrn_stats = effects.add_to_vcf(data["vrn_file"], data)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 33, in add_to_vcf

    ann_vrn_file = run_vep(in_file, data)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 150, in run_vep

    do.run(cmd, "Ensembl variant effect predictor", data)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run

    _do_run(cmd, checks, log_stdout)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run

    raise subprocess.CalledProcessError(exitcode, error_msg)

subprocess.CalledProcessError: Command 'set -o pipefail; /usr/local/bin/variant_effect_predictor.pl --vcf -o stdout -i /mnt/work/freebayes/batch24.vcf.gz --fork 5 --species homo_sapiens --no_stats --cache --offline --dir /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/vep --sift b --polyphen b --symbol --numbers --biotype --total_length --canonical --ccds --fields Consequence,Codons,Amino_acids,Gene,SYMBOL,Feature,EXON,PolyPhen,SIFT,Protein_position,BIOTYPE,CANONICAL,CCDS,LoF,LoF_filter,LoF_flags --plugin LoF,human_ancestor_fa:/usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/variation/human_ancestor.fa.gz | sed '/^#/! s/;;/;/g' | bgzip -c > /mnt/work/freebayes/tx/tmpekR8KC/batch24-vepeffects.vcf.gz

Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /usr/local/Cellar/vep/81_2015-07-23/lib/Plugins /usr/local/Cellar/vep/81_2015-07-23/lib /usr/local/bin /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.

Compilation failed in require at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 68.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 68.

Compilation failed in require at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Registry.pm line 136.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Registry.pm line 136.

Compilation failed in require at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Variation/Utils/VEP.pm line 64.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Variation/Utils/VEP.pm line 64.

Compilation failed in require at /usr/local/bin/variant_effect_predictor.pl line 72.

BEGIN failed--compilation aborted at /usr/local/bin/variant_effect_predictor.pl line 72.

' returned non-zero exit status 2

Uncaught exception occurred

Traceback (most recent call last):

  File "/Users/alessandro/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.1a0-py2.7.egg/bcbio/provenance/do.py", line 21, in run

    _do_run(cmd, checks, log_stdout)

  File "/Users/alessandro/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.1a0-py2.7.egg/bcbio/provenance/do.py", line 95, in _do_run

    raise subprocess.CalledProcessError(exitcode, error_msg)

CalledProcessError: Command 'docker attach --no-stdin 7bf5d3353977c7c0e278215f9dde61fc061b2ee36198d3e5ca5db2bb373ce834

[2015-08-09T04:41Z] tabix index batch19-15_90631730_102531392.vcf.gz

[2015-08-09T04:41Z] tabix index batch19-16_0_67063480.vcf.gz

[2015-08-09T04:41Z] tabix index batch19-16_67063593_90354753.vcf.gz

[2015-08-09T04:41Z] tabix index batch19-17_0_29422398.vcf.gz

[2015-08-09T04:41Z] tabix index batch19-17_29482773_81195210.vcf.gz

[2015-08-09T04:41Z] .........10.........20.........30.........40.........50........

[2015-08-09T04:41Z] tabix index batch19-18_0_78077248.vcf.gz

[2015-08-09T04:41Z] tabix index batch19-19_0_56166105.vcf.gz

[2015-08-09T04:41Z] tabix index batch19-19_56166368_59128983.vcf.gz

[2015-08-09T04:41Z] tabix index batch19-20_0_62037953.vcf.gz

[2015-08-09T04:41Z] tabix index batch19-20_62038116_63025520.vcf.gz

[2015-08-09T04:41Z] tabix index batch19-21_0_48129895.vcf.gz

[2015-08-09T04:41Z] tabix index batch19-22_0_51304566.vcf.gz

[2015-08-09T04:41Z] tabix index batch19-X_0_15509536.vcf.gz

[2015-08-09T04:41Z] tabix index batch19-X_15808523_155270560.vcf.gz

[2015-08-09T04:41Z] Concat variant files

[2015-08-09T04:41Z] /usr/local/bin/gatk-framework: line 7: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory

[2015-08-09T04:41Z] INFO  04:41:11,814 HelpFormatter - -------------------------------------------------------

[2015-08-09T04:41Z] INFO  04:41:11,817 HelpFormatter - Program Name: org.broadinstitute.gatk.tools.CatVariants

[2015-08-09T04:41Z] INFO  04:41:11,860 HelpFormatter - Program Args: -R /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -V /mnt/work/vardict/batch19-files.list -out /mnt/work/vardict/tx/tmp8cZgxH/batch19.vcf.gz -assumeSorted

[2015-08-09T04:41Z] INFO  04:41:11,877 HelpFormatter - Executing as root@dev on Linux 4.0.7-boot2docker amd64; OpenJDK 64-Bit Server VM 1.7.0_79-b14.

[2015-08-09T04:41Z] INFO  04:41:11,878 HelpFormatter - Date/Time: 2015/08/09 04:41:11

[2015-08-09T04:41Z] INFO  04:41:11,878 HelpFormatter - -------------------------------------------------------

[2015-08-09T04:41Z] INFO  04:41:11,879 HelpFormatter - -------------------------------------------------------

[2015-08-09T04:41Z] .........10.........20.........30.........40.........50.......

[2015-08-09T04:41Z] Resource requests: bamtools, bcbio_variation, fastqc, gatk, gemini, qsignature, samtools; memory: 2.00, 0.31, 2.00, 0.44, 2.00, 0.25, 2.00; cores: 16, 1, 16, 1, 16, 1, 16

[2015-08-09T04:41Z] Configuring 1 jobs to run, using 5 cores each with 11.4g of memory reserved for each job

[2015-08-09T04:41Z] Timing: joint squaring off/backfilling

[2015-08-09T04:41Z] Timing: variant post-processing

[2015-08-09T04:41Z] multiprocessing: postprocess_variants

[2015-08-09T04:41Z] Finalizing variant calls: 24, freebayes

[2015-08-09T04:41Z] Calculating variation effects for 24, freebayes

[2015-08-09T04:41Z] Ensembl variant effect predictor : 24

[2015-08-09T04:41Z] Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /usr/local/Cellar/vep/81_2015-07-23/lib/Plugins /usr/local/Cellar/vep/81_2015-07-23/lib /usr/local/bin /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.

[2015-08-09T04:41Z] BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.

[2015-08-09T04:41Z] Uncaught exception occurred

Traceback (most recent call last):

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run

    _do_run(cmd, checks, log_stdout)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run

    raise subprocess.CalledProcessError(exitcode, error_msg)

CalledProcessError: Command 'set -o pipefail; /usr/local/bin/variant_effect_predictor.pl --vcf -o stdout -i /mnt/work/freebayes/batch24.vcf.gz --fork 5 --species homo_sapiens --no_stats --cache --offline --dir /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/vep --sift b --polyphen b --symbol --numbers --biotype --total_length --canonical --ccds --fields Consequence,Codons,Amino_acids,Gene,SYMBOL,Feature,EXON,PolyPhen,SIFT,Protein_position,BIOTYPE,CANONICAL,CCDS,LoF,LoF_filter,LoF_flags --plugin LoF,human_ancestor_fa:/usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/variation/human_ancestor.fa.gz | sed '/^#/! s/;;/;/g' | bgzip -c > /mnt/work/freebayes/tx/tmpekR8KC/batch24-vepeffects.vcf.gz

Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /usr/local/Cellar/vep/81_2015-07-23/lib/Plugins /usr/local/Cellar/vep/81_2015-07-23/lib /usr/local/bin /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.

Compilation failed in require at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 68.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 68.

Compilation failed in require at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Registry.pm line 136.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Registry.pm line 136.

Compilation failed in require at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Variation/Utils/VEP.pm line 64.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Variation/Utils/VEP.pm line 64.

Compilation failed in require at /usr/local/bin/variant_effect_predictor.pl line 72.

BEGIN failed--compilation aborted at /usr/local/bin/variant_effect_predictor.pl line 72.

' returned non-zero exit status 2

Traceback (most recent call last):

  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>

    main(**kwargs)

  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main

    run_main(**kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main

    fc_dir, run_info_yaml)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel

    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 174, in run

    samples = run_parallel("postprocess_variants", samples)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel

    return run_multicore(fn, items, config, parallel=parallel)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore

    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__

    self.dispatch(function, args, kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch

    job = ImmediateApply(func, args, kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__

    self.results = func(*args, **kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper

    return apply(f, *args, **kwargs)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 68, in postprocess_variants

    return variation.postprocess_variants(*args)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/variation.py", line 18, in postprocess_variants

    ann_vrn_file, vrn_stats = effects.add_to_vcf(data["vrn_file"], data)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 33, in add_to_vcf

    ann_vrn_file = run_vep(in_file, data)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 150, in run_vep

    do.run(cmd, "Ensembl variant effect predictor", data)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run

    _do_run(cmd, checks, log_stdout)

  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run

    raise subprocess.CalledProcessError(exitcode, error_msg)

subprocess.CalledProcessError: Command 'set -o pipefail; /usr/local/bin/variant_effect_predictor.pl --vcf -o stdout -i /mnt/work/freebayes/batch24.vcf.gz --fork 5 --species homo_sapiens --no_stats --cache --offline --dir /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/vep --sift b --polyphen b --symbol --numbers --biotype --total_length --canonical --ccds --fields Consequence,Codons,Amino_acids,Gene,SYMBOL,Feature,EXON,PolyPhen,SIFT,Protein_position,BIOTYPE,CANONICAL,CCDS,LoF,LoF_filter,LoF_flags --plugin LoF,human_ancestor_fa:/usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/variation/human_ancestor.fa.gz | sed '/^#/! s/;;/;/g' | bgzip -c > /mnt/work/freebayes/tx/tmpekR8KC/batch24-vepeffects.vcf.gz

Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /usr/local/Cellar/vep/81_2015-07-23/lib/Plugins /usr/local/Cellar/vep/81_2015-07-23/lib /usr/local/bin /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.

Compilation failed in require at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 68.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 68.

Compilation failed in require at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Registry.pm line 136.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Registry.pm line 136.

Compilation failed in require at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Variation/Utils/VEP.pm line 64.

BEGIN failed--compilation aborted at /usr/local/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Variation/Utils/VEP.pm line 64.

Compilation failed in require at /usr/local/bin/variant_effect_predictor.pl line 72.

BEGIN failed--compilation aborted at /usr/local/bin/variant_effect_predictor.pl line 72.

' returned non-zero exit status 2

' returned non-zero exit status 1

Stopping docker container

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. DBI and other Perl modules are installed in the docker container but it looks like they're not being properly exported. I pushed a fix to set `PERL5LIB` correctly which should ensure this works in the future. You can update by getting the latest version of the wrapper code:
```
bcbio_vm.py upgrade --wrapper
```
and hopefully it'll work correctly for you now. Thanks again.
